[info]
format_version = "0.0.1"
description = "List of actions to be done with SPI NOR"
build_id = "@BUILD_ID@"

[profile.recovery]
bootrom.description = "Flash SBIMG parsed by BootROM"
bootrom.command = "flash"
bootrom.name = "@BOOTROM_SBIMG@"

sbl.description = "Flash SBIMG parsed by SBL"
sbl.command = "flash"
sbl.name = "@SBL_SBIMG@"
sbl.offset = 0xA10000

sbl_env.description = "Erase SBL environment"
sbl_env.command = "erase"
sbl_env.offset = 0x30000
sbl_env.size = 0x10000
sbl_env.negative_offset = true

uboot_env.description = "Erase U-Boot environment"
uboot_env.command = "erase"
uboot_env.offset = 0xFE0000
uboot_env.size = 0x10000
